// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/App/Bar.vue')['default']
    AppNavigation: typeof import('./src/components/App/Navigation.vue')['default']
    BaseCard: typeof import('./src/layouts/BaseCard.vue')['default']
    Effects: typeof import('./src/views/Effects/index.vue')['default']
    Factory: typeof import('./src/views/Factory/index.vue')['default']
    FactoryActiveProductions: typeof import('./src/views/Factory/components/ActiveProductions.vue')['default']
    FactoryInactiveProductions: typeof import('./src/views/Factory/components/InactiveProductions.vue')['default']
    IconMdiClock: typeof import('~icons/mdi/clock')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiHammer: typeof import('~icons/mdi/hammer')['default']
    Inventory: typeof import('./src/views/Inventory/index.vue')['default']
    Science: typeof import('./src/views/Science/index.vue')['default']
    Stats: typeof import('./src/views/Stats/index.vue')['default']
  }
}

export { }
