// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/App/Bar.vue')['default']
    AppNavigation: typeof import('./src/components/App/Navigation.vue')['default']
    BaseButton: typeof import('./src/components/Base/Button.vue')['default']
    BaseCard: typeof import('./src/layouts/BaseCard.vue')['default']
    BaseDialog: typeof import('./src/components/Base/Dialog.vue')['default']
    BaseProgressBar: typeof import('./src/components/Base/ProgressBar.vue')['default']
    BaseTable: typeof import('./src/components/Base/Table.vue')['default']
    Effects: typeof import('./src/views/Effects/index.vue')['default']
    Factory: typeof import('./src/views/Factory/index.vue')['default']
    FactoryActiveProductions: typeof import('./src/views/Factory/components/ActiveProductions.vue')['default']
    FactoryInactiveProductions: typeof import('./src/views/Factory/components/InactiveProductions.vue')['default']
    Game: typeof import('./src/views/Game/index.vue')['default']
    'IconHealthicons:moneyBag': typeof import('~icons/healthicons/money-bag')['default']
    IconMdiClock: typeof import('~icons/mdi/clock')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiHammer: typeof import('~icons/mdi/hammer')['default']
    IconMdiPause: typeof import('~icons/mdi/pause')['default']
    IconMdiPlay: typeof import('~icons/mdi/play')['default']
    Inventory: typeof import('./src/views/Inventory/index.vue')['default']
    Sale: typeof import('./src/views/Sale/index.vue')['default']
    SaleDialog: typeof import('./src/views/Sale/components/Dialog.vue')['default']
    Science: typeof import('./src/views/Science/index.vue')['default']
    Stats: typeof import('./src/views/Stats/index.vue')['default']
  }
}

export { }
