// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Achievements: typeof import('./src/views/Achievements/index.vue')['default']
    AppBar: typeof import('./src/components/App/Bar.vue')['default']
    AppNavigation: typeof import('./src/components/App/Navigation.vue')['default']
    BaseButton: typeof import('./src/components/Base/Button.vue')['default']
    BaseCard: typeof import('./src/layouts/BaseCard.vue')['default']
    BaseDialog: typeof import('./src/components/Base/Dialog.vue')['default']
    BaseProgressBar: typeof import('./src/components/Base/ProgressBar.vue')['default']
    BaseTable: typeof import('./src/components/Base/Table.vue')['default']
    Effects: typeof import('./src/views/Effects/index.vue')['default']
    Factory: typeof import('./src/views/Factory/index.vue')['default']
    FactoryActiveProductions: typeof import('./src/views/Factory/components/ActiveProductions.vue')['default']
    FactoryInactiveProductions: typeof import('./src/views/Factory/components/InactiveProductions.vue')['default']
    Game: typeof import('./src/views/Game/index.vue')['default']
    'IconFontisto:laboratory': typeof import('~icons/fontisto/laboratory')['default']
    'IconIc:baselineAttachMoney': typeof import('~icons/ic/baseline-attach-money')['default']
    'IconIc:roundScience': typeof import('~icons/ic/round-science')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiExport: typeof import('~icons/mdi/export')['default']
    IconMdiHammer: typeof import('~icons/mdi/hammer')['default']
    IconMdiImport: typeof import('~icons/mdi/import')['default']
    IconMdiPause: typeof import('~icons/mdi/pause')['default']
    IconMdiPlay: typeof import('~icons/mdi/play')['default']
    IconMdiSitemap: typeof import('~icons/mdi/sitemap')['default']
    Inventory: typeof import('./src/views/Inventory/index.vue')['default']
    InventoryItemTable: typeof import('./src/views/Inventory/components/ItemTable.vue')['default']
    InventoryStorageSpaceCard: typeof import('./src/views/Inventory/components/StorageSpaceCard.vue')['default']
    Library: typeof import('./src/views/Library/index.vue')['default']
    LibraryItemTable: typeof import('./src/views/Library/components/ItemTable.vue')['default']
    Sale: typeof import('./src/views/Sale/index.vue')['default']
    SaleDialog: typeof import('./src/views/Sale/components/Dialog.vue')['default']
    Science: typeof import('./src/views/Science/index.vue')['default']
    ScienceCurrentResearchCard: typeof import('./src/views/Science/components/CurrentResearchCard.vue')['default']
    Stats: typeof import('./src/views/Stats/index.vue')['default']
    Tools: typeof import('./src/views/Tools/index.vue')['default']
  }
}

export { }
