name: Build Vue

on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: alexvoedi/VuePagesAction@2.0.0
      with:
        username: 'alexvoedi'
        reponame: 'idle-game'
        token: ${{ secrets.GITHUB_TOKEN }}
        packagemanager: 'pnpm'
